version: "3.8"

services:
  gogin:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    container_name: gogin
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
    command: [ "air", "-c", "dev/.air.conf" ]
    healthcheck:
      test: curl --fail -s http://localhost:8000/ping || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
volumes:
  gomod:
  gocache:
networks:
  default:
    name: goauth-net
    ipam:
      driver: default
      config:
      - subnet:  172.22.0.0/16