version: "3.8"

services:
  goauth-be:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./dev/Dockerfile
    container_name: goauth-be
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - gomod:/go/pkg/mod
      - gocache:/root/.cache/go-build
    command: [ "air", "-c", "dev/.air.conf" ]
    restart: unless-stopped
    healthcheck:
      test: curl --fail -s http://localhost:8000/api/ping || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  goauth-fe:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: goauth-fe
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      # - gomodules:/app/node_modules
      # - gonext:/app/.next
    ports:
      - 8001:3000
volumes:
  gomod:
  gocache:
networks:
  default:
    name: goauth-net
    ipam:
      driver: default
      config:
      - subnet:  172.22.0.0/16