global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'goauth'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:8000']
      
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['host.docker.internal:5100']
      # - targets: ['172.17.0.1:5100']
