// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package handler is a generated GoMock package.
package handler

import (
	gomock "github.com/golang/mock/gomock"
)

// MockIAuthUseCase is a mock of IAuthUseCase interface.
type MockIAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthUseCaseMockRecorder
}

// MockIAuthUseCaseMockRecorder is the mock recorder for MockIAuthUseCase.
type MockIAuthUseCaseMockRecorder struct {
	mock *MockIAuthUseCase
}

// NewMockIAuthUseCase creates a new mock instance.
func NewMockIAuthUseCase(ctrl *gomock.Controller) *MockIAuthUseCase {
	mock := &MockIAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockIAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthUseCase) EXPECT() *MockIAuthUseCaseMockRecorder {
	return m.recorder
}
